<?php
# This file was automatically generated by the MediaWiki 1.44.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}




## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Royaltek Wiki";
$wgMetaNamespace = "Royaltek_Wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://192.168.145.166:8050";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
	'icon' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "mysql";
$wgDBname = "mediawiki";
$wgDBuser = "mediawiki";
$wgDBpassword = "mediawiki_password";

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# Set maximum upload file size to 500MB
$wgMaxUploadSize = 500 * 1024 * 1024; // 500MB in bytes
$wgUploadSizeWarning = 450 * 1024 * 1024; // Warning at 450MB

# Enable support for many file formats
$wgFileExtensions = array_merge(
    $wgFileExtensions,
    [
        // Documents
        'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'odt', 'ods', 'odp',
        'rtf', 'txt', 'csv',

        // Images (additional formats)
        'svg', 'tiff', 'tif', 'bmp', 'ico', 'psd',

        // Audio
        'mp3', 'wav', 'ogg', 'flac', 'm4a', 'aac',

        // Video
        'mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mkv',

        // Archives
        'zip', 'rar', '7z', 'tar', 'gz', 'bz2',

        // Code/Text files
        'xml', 'json', 'css', 'js', 'php', 'py', 'java', 'cpp', 'c', 'h',

        // Other formats
        'epub', 'mobi', 'dwg', 'dxf', 'step', 'stp', 'iges', 'igs'
    ]
);

# Allow uploads of executable files (be careful with security)
$wgStrictFileExtensions = false; // Shows warning instead of blocking

# MsUpload extension configuration
$wgMSU_useDragDrop = true; // Enable drag & drop uploads
$wgMSU_showAutoCat = true; // Show category options
$wgMSU_checkAutoCat = true; // Auto-check category option
$wgMSU_confirmReplace = true; // Confirm before replacing files

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "zh-tw";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "0b849211a4eccaf24cc4dd15e0c39e3ecf7c9c5422d2496b5e3114177440c968";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "cfb915fc5862d6e0";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'Interwiki' );
wfLoadExtension( 'Linter' );
wfLoadExtension( 'Math' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'ReplaceText' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'WikiMarkdown' );
wfLoadExtension( 'Diagrams' );
wfLoadExtension( 'EmbedVideo' );
# wfLoadExtension( 'MsUpload' ); // Temporarily disabled until installation is fixed


# End of automatically generated settings.
# Add more configuration options below.

# WikiMarkdown extension additional configuration
$wgAllowMarkdownExtra = true; // allows usage of Parsedown Extra
$wgAllowMarkdownExtended = true; // allows usage of Parsedown Extended

# VisualEditor configuration
$wgDefaultUserOptions['visualeditor-enable'] = 1;
$wgDefaultUserOptions['visualeditor-editor'] = "visualeditor";
$wgVisualEditorAvailableNamespaces = [
    NS_MAIN => true,
    NS_USER => true,
    NS_PROJECT => true,
    NS_HELP => true,
    NS_CATEGORY => true
];
# Use built-in Parsoid (MediaWiki 1.44 includes Parsoid)
$wgVisualEditorRestbaseURL = false;
$wgVisualEditorFullRestbaseURL = false;

# Diagrams extension configuration
$wgDiagramsLocalCommands = [
    'mscgen' => '/usr/bin/mscgen',
    'plantuml' => '/usr/local/bin/plantuml',
    'dot' => '/usr/bin/dot',
    'neato' => '/usr/bin/neato',
    'fdp' => '/usr/bin/fdp',
    'sfdp' => '/usr/bin/sfdp',
    'circo' => '/usr/bin/circo',
    'twopi' => '/usr/bin/twopi',
    'osage' => '/usr/bin/osage'
];

# EmbedVideo extension configuration
$wgEmbedVideoMinWidth = 300;
$wgEmbedVideoMaxWidth = 800;
$wgEmbedVideoDefaultWidth = 640;
$wgEmbedVideoEnableVideoHandler = true;
$wgEmbedVideoEnableAudioHandler = true;
$wgFFmpegLocation = '/usr/bin/ffmpeg';

# Enable detailed error reporting for debugging
$wgShowExceptionDetails = true;

